-- Create database
drop table following_table if exists
drop table post if exists
drop table user if exists
create table following_table (fid bigint generated by default as identity, uid bigint not null, followed_id bigint not null)
create table post (pid bigint generated by default as identity, text varchar(255), title varchar(255) not null, uid bigint, primary key (pid), date_created timestamp)
create table user (uid bigint generated by default as identity, name varchar(255) not null, primary key (uid))
alter table user add constraint user_unique_name unique (name)

alter table following_table add constraint no_duplicated_following unique (uid, followed_id)
alter table following_table add constraint no_duplicated_followed unique (followed_id, uid)
alter table following_table add constraint no_self_following check (uid != followed_id)

alter table following_table add constraint following_table_followed_id_fk foreign key (followed_id) references user
alter table following_table add constraint following_table_uid_fk foreign key (uid) references user
alter table post add constraint post_uid_fk foreign key (uid) references user


--Insert example data
insert into user (NAME) values('adam');
insert into user (name) values ('user1')
insert into user (name) values ('user2')

insert into post (title, text, uid,date_created) values ('Post title','text of post',1,parsedatetime('17-01-2017 18:37:52', 'dd-MM-yyyy hh:mm:ss'))
insert into post (title, text, uid,date_created) values ('Post title 2','text of post2',2,parsedatetime('17-01-2015 12:37:52', 'dd-MM-yyyy hh:mm:ss'))
insert into post (title, text, uid,date_created) values ('Post title 2','text 123',2,parsedatetime('17-01-2016 14:37:52', 'dd-MM-yyyy hh:mm:ss'))

insert into following_table (uid,followed_id) values ('1','2')
insert into following_table (uid,followed_id) values ('2','1')


